version: '3.7'

services:

  redisdb:
    image: redis
    ports:
      - "6379:6379"
    container_name: redisdb
    networks: 
      - api-network-driver

  api-watson-assistant:
    build:
      context: .
      dockerfile: dockerfile
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - redisdb
    image: api-watson-assistant
    container_name: api-watson-assistant
    networks: 
      - api-network-driver

networks:
  api-network-driver:
     name: api-network-driver